### ISSUE TITLE
Use travis

### ISSUE THREAD

**Issue by hadley** [rstats-db/RPostgres#1]
(Once @jeroenooms has improved the build scripts)

**Comment by jeroenooms** [comment]
FYI I'm looking into this but having a hard time building libpq as a static library on windows. The standard setup only generates dynamic/import library of libpq. But that's ugly because we would have to ship dll files for libpq, openssl, etc, with the package.

**Comment by hadley** [comment]
@jeroenooms how does RPostgreSQL currently work on windows? It assumes libpq is installed already?

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/rstats-db/RPostgres/pull/8.
