### ISSUE TITLE
Configuration failed because libpq was not found.

### ISSUE THREAD

**Issue by JackStat** [rstats-db/RPostgres#118]
@jeroen after the latest 5 or so commits (one of them was messaged "Aggh who broke my shit" haha). My shit was broken... If I do an install to commit https://github.com/rstats-db/RPostgres/commit/f1835d31a7a5fd72a7877ee63d851ebedf2a3d9e everything works fine.  Let me know if I can do anything to help fix the issue and as always thanks for everything you do.

```
Using pg_config includedir and libdir!
Using PKG_CFLAGS=
Using PKG_LIBS=-lpq
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libpq was not found. Try installing:
 * deb: libpq-dev (Debian, Ubuntu, etc)
 * rpm: postgresql-devel (Fedora, EPEL)
 * rpm: postgreql8-devel, psstgresql92-devel, postgresql93-devel, or postgresql94-devel (Amazon Linux)
 * csw: postgresql_dev (Solaris)
 * brew: postgresql (OSX)
If libpq is already installed, check that either:
(i)  'pkg-config' is in your PATH AND PKG_CONFIG_PATH contains
     a libpq.pc file; or
(ii) 'pg_config' is in your PATH.
If neither can detect , you can set INCLUDE_DIR
and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```

**Comment by jeroen** [comment]
Hmm your `pkg-config` is giving these values, so that means something is misconfigured on your system. Can you please show the output of the successful install? In particular the lines with `Using PKG_CFLAGS` and `Using PKG_LIBS=`...

**Comment by JackStat** [comment]
hmm I am doing a fresh build of a docker image that was based on your opencpu dockerfile.  Let me see if I can reproduce it with the dockerfile

**Comment by usman-r** [comment]
I've got a [PR](https://github.com/rstats-db/RPostgres/pull/119) that fixes this issue.

**Comment by mmuurr** [comment]
@jeroen I think I'm the one who "broke [...] shit" with #81 , but I'd argue that #81 (merged at 3f8dcf7) might also fix this issue.
(@JackStat can you try 3f8dcf7 and echo the installation output?)

I've found a bunch of PostgreSQL installations over the years (on particular Linux distros, e.g. Amazon Linuxes) where some combination of these are true:
* pkg_config specifying _only_ **one** of cflags or libs
* pg_config specifying _only_ **one** of includedir or libdir
* the above two cases not complementing each other forcing me to manually specify one _or_ the other of INCLUDE_DIR or LIB_DIR (but not necessarily both) as an arg to RPostgres' installation.

Thus, #81 tried to factor these two variables out into their own value-discovery paths.
For both variables, highest priority is an arg given at package-install time, then pkg_config, then pg_config, then (finally) brew if on darwin*.
@JackStat's problem smells like exactly this sort of scenario where only one of the two values are being reported by either pg_config or pkg_config.

Being able to pass exactly one of INCLUDE_DIR or LIB_DIR (i.e. without having to necessarily pass both) at installation-time seems like a good enough reason (IMHO) to treat these two variables separately during installation, but I'm happy to defer to the original author.
Definitely not trying to rock-the-boat here, and thanks a ton for all the work/contributing you put in to these projects.

**Comment by guilherme** [comment]
@JackStat It worked for me when I installed both: libpq-dev and pkg-config

**Comment by kanxuUCHI** [comment]
Bumped into this issue and @guilherme 's method works for me as well.

**Comment by vikram-rawat** [comment]
Hi,

Got the same issue like this one today while trying to create a docker file from windows.  Is there a solution to fix it yet...

Ticket seems to be closed..

**Comment by krlmlr** [comment]
Please open a new issue with a precise description. What output are you seeing? Have you installed `libpq-dev`?
