### ISSUE TITLE
Uploading text columns adds extra set of single quotes

### ISSUE THREAD

**Issue by richfitz** [rstats-db/RPostgres#125]
On upload of character data via `DBI::dbWriteTable` I am seeing quote marks surrounding all the data

Using postgres 9.6.2 in a docker container

```
docker run -p 5555:5432 postgres:9.6.2
```

```r
con <- DBI::dbConnect(RPostgres::Postgres(),
                      dbname = "postgres",
                      host = "localhost",
                      port = 5555,
                      user = "postgres")
d <- data.frame(a = letters, b = LETTERS)
DBI::dbWriteTable(con, "foo", d)
DBI::dbReadTable(con, "foo")
````

gives

```
     a   b
1  'a' 'A'
2  'b' 'B'
3  'c' 'C'
4  'd' 'D'
5  'e' 'E'
6  'f' 'F'
7  'g' 'G'
8  'h' 'H'
9  'i' 'I'
10 'j' 'J'
...
```

psql confirms this is an upload rather than a download issue

```
postgres=# SELECT * from foo;
  a  |  b  
-----+-----
 'a' | 'A'
 'b' | 'B'
 'c' | 'C'
 'd' | 'D'
 'e' | 'E'
 'f' | 'F'
 'g' | 'G'
 'h' | 'H'
 'i' | 'I'
 'j' | 'J'
...
 ```

**Comment by richfitz** [comment]
This is with version 71a936d

**Comment by richfitz** [comment]
And confirmed OK as of tag v0.1-4 - looks like this is showing up in your travis builds too: https://travis-ci.org/rstats-db/RPostgres#L2044

**Comment by thrasibule** [comment]
This is due to commit 533fab0. I think this commit should be reverted. The encoding of strings is already done in https://github.com/rstats-db/RPostgres/blob/master/src/encode.cpp#L96.

**Comment by krlmlr** [comment]
Thanks for your help, please open a new issue in case of further problems.
