### ISSUE TITLE
Insallation error brand new machine

### ISSUE THREAD

**Issue by 2sls** [rstats-db/RPostgres#127]
I had issues with installing this package on one machine and did a fresh install of Windows 10 x64 Pro

I am running R 3.2.1 with Rstudio 1.0.153

The installation returns the following - any ideas?

*** arch - x64
rm -f RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o RPostgres.dll
"C:/PROGRA~1/R/R-34~1.1/bin/x64/Rscript.exe" "../tools/winlibs.R"
Error: package 'RPostgres' is not installed for 'arch = x64'
Execution halted
make: *** [winlibs] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="RPostgres.dll" WIN=64 TCLBIN=64 OBJECTS="RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o"' had status 2
ERROR: compilation failed for package 'RPostgres'
* removing 'C:/Users/Documents/R/win-library/3.4/RPostgres'

**Comment by 2sls** [comment]
Subsequent re installation attempts give the following message:
> devtools::install_github("rstats-db/RPostgres")
Downloading GitHub repo rstats-db/RPostgres@master
from URL https://api.github.com/repos/rstats-db/RPostgres/zipball/master
Installing RPostgres
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/AppData/Local/Temp/RtmpYZO007/devtools19ec340736dd/rstats-db-RPostgres-449caf1"  \
  --library="C:/Users/Documents/R/win-library/3.4" --install-tests 

Error in library(RPostgres) : there is no package called 'RPostgres'
Execution halted
Installation failed: Command failed (1)

**Comment by 2sls** [comment]
I removed and reinstalled R and then I could suddenly install the package, but issue is now that the package timeouts in connecting to any remote server. My other machine installed without a hitch so I am really stumped on how a fresh windows install isn't working still. I feel like I'm missing something.

**Comment by krlmlr** [comment]
Firewall maybe? Looks like the installation and connectivity problems you're experiencing are really two different problems.
