### ISSUE TITLE
dbConnect complains that Rcpp >= 0.11.4.2 is required although Rcpp 0.11.4.5 is loaded

### ISSUE THREAD

**Issue by andreskull** [rstats-db/RPostgres#16]
> con <- dbConnect(RPostgres::Postgres())
Error in is(object, Cl) : 
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Rcpp’ 0.11.4 is already loaded, but >= 0.11.4.2 is required

sessionInfo() shows that I have Rcpp_0.11.4.5  loaded via namespace

**Comment by hadley** [comment]
Restart R?

**Comment by andreskull** [comment]
Thanks for the hint! This helped.
