### ISSUE TITLE
Package install failed on ubuntu

### ISSUE THREAD

**Issue by AlunHewinson** [rstats-db/RPostgres#17]
Tried to install this on an ubuntu virtual machine:

```
devtools::install_github("RcppCore/Rcpp") # done successfully
devtools::install_github("rstats-db/DBI") # done successfully
devtools::install_github("rstats-db/SQL") # done successfully
devtools::install_github("rstats-db/RPostgres") # attempting...
```

Package installation failed with the following message:

```
In file included from PqResult.h:9:0,
                 from RPostgres_types.h:5,
                 from RcppExports.cpp:4:
PqRow.h: In member function ‘bool PqRow::hasData()’:
PqRow.h:45:24: error: ‘PGRES_SINGLE_TUPLE’ was not declared in this scope
In file included from RPostgres_types.h:5:0,
                 from RcppExports.cpp:4:
PqResult.h: In member function ‘void PqResult::bind()’:
PqResult.h:82:43: error: ‘PQsetSingleRowMode’ was not declared in this scope
PqResult.h: In member function ‘void PqResult::bind(Rcpp::ListOf<Rcpp::Vector<16> >)’:
PqResult.h:104:43: error: ‘PQsetSingleRowMode’ was not declared in this scope
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘RPostgres’
* removing ‘/home/vagrant/.rpackages/RPostgres’
Error: Command failed (1)
```

My system info:
```Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86
_64 x86_64 x86_64 GNU/Linux```

R running in RStudio
```$version.string
[1] "R version 3.1.2 (2014-10-31)"
```

**Comment by hadley** [comment]
Hmmmm, what version of libpq-dev do you have installed?

**Comment by jeroenooms** [comment]
His sessioninfo says precise so it's probably [this one](http://packages.ubuntu.com/precise/libpq-dev).

**Comment by jeroenooms** [comment]
Although, travis runs this same version of ubuntu and there we are not seeing this error. So maybe he uses a non-stock version.

**Comment by AlunHewinson** [comment]
```
Package: libpq-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 876
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: postgresql-9.1
Version: 9.1.15-0ubuntu0.12.04
Replaces: postgresql-dev
Depends: libc6 (>= 2.4), libpq5 (= 9.1.15-0ubuntu0.12.04), libssl-dev, libkrb5-d
ev, comerr-dev
Suggests: postgresql-doc-9.1
Conflicts: postgresql-dev (<< 7.5)
Description: header files for libpq5 (PostgreSQL library)
 Header files and static library for compiling C programs to link
 with the libpq library in order to communicate with a PostgreSQL
 database backend.
 .
 PostgreSQL is an object-relational SQL database management system.
Homepage: http://www.postgresql.org/
Original-Maintainer: Martin Pitt <mpitt@debian.org>
```

**Comment by mbannert** [comment]
The old elephant has been taught quite a few new tricks in more recent versions... particularly with the NoSQL stuff like hstore and json. You could try upgrading to 9.3 ?

**Comment by AlunHewinson** [comment]
By "the old elephant", I take it you mean PostgreSQL (perhaps it's best to avoid jargony expressions like that, since it may confuse people with little experience of this type of thing, like me).

When running
```
sudo apt-get install postgresql postgresql-contrib
```
Ubuntu tries to install v9.1; as I understand it, the above `apt-get` installs the latest version available to my operating system.
I'll admit to being out of my depth here.  I don't know whether this is a fault in this package or not.  If anybody else has something to contribute or you want me to test on my system, please let me know but don't assume any knowledge on my part.
Ubuntu is running on a virtual machine, so I *can* experiment and destroy and rebuild the machine if things go badly wrong.

**Comment by krlmlr** [comment]
Hm... I had no trouble installing it on Ubuntu 15.04.

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.
