### ISSUE TITLE
Password prompt and SSL

### ISSUE THREAD

**Issue by mbannert** [rstats-db/RPostgres#26]
I am not sure whether RPostgres is the right place to implement such a thing but I've been looking / working around this for a while when working with databases and R:
- Would it possible to have something like `.rs.askForPassword` on the R console? 
- Can communication between the database and R be encrypted?

**Comment by hadley** [comment]
I've thought about boostrapping something simple with a tiny shiny app (using `shiny::stopApp()`). 

RPostgres should always build with SSL support, so you just need to set the appropriate Postgres options (which I know nothing about :/)

**Comment by mbannert** [comment]
Ok nice to know that SSL is supported. If also played around with a tiny shiny app in my timeseriesdb application. The `passwordInput()` functions works great. The only thing I don't like about the idea is that the password is stored in the shiny session in `input`. I tried to delete / overwrite it after the connection is created but I could figure a way around the fact that input is read only in shiny. Even though can put SSL in front of the shiny session, too it would be nice to remove the password from the session, also for local use.

**Comment by hadley** [comment]
I was thinking of something like this:

```R
library(shiny)

loginApp <- shinyApp(
  basicPage(
    textInput("username", "User name"),
    passwordInput("password", "Password"),
    shiny::actionButton("submit", "Submit")
  ),
  function(input, output) {
    observe({
      if (input$submit != 0)
        stopApp(list(
          username = isolate(input$username), 
          password = isolate(input$password)
        ))
    })
  }
)

login <- runApp(loginApp)
```

(for local use, to avoid people entering username/password into the console)

**Comment by mbannert** [comment]
Nice. I had the first part too, but `stopApp()` is actually a neat addition, especially if you use Rstudio's viewer and not the browser... Also, you could include a check for R Studio Server, and if R Studio server is detected `rs.askForPassword` is used instead. Thanks for sharing.

**Comment by hadley** [comment]
It would be helpful to wrap this up into a little package... (but I'm closing this issue now since it's not really RPostgres specific)
