### ISSUE TITLE
Error: Lost connection to database

### ISSUE THREAD

**Issue by sqlscissors** [rstats-db/RPostgres#31]
Hi,
I am getting the following error in RPostgres package after I ran

dbGetQuery(con,query)

Error: Lost connection to database

 dbDisconnect(con)
[1] TRUE
Warning message:
In connection_release(conn@ptr) : There is a result object still in use.
The connection will be automatically released when it is closed

Then I ran dbClearResults(con) and I get the following error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbClearResult’ for signature ‘"PqConnection"’

Can you please tell me how to clear the resultset?

**Comment by krlmlr** [comment]
Thanks. This is a bit too vague -- does this happen with specific queries? What are your R, RPostgres, and PostgreSQL versions?

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.
