### ISSUE TITLE
Install failed on WIndows

### ISSUE THREAD

**Issue by bmaitner** [rstats-db/RPostgres#36]
When trying to install the package from CRAN, I get the following error:

* installing *source* package 'RPostgres' ...
Warning: running command 'sh ./configure.win' had status 127
ERROR: configuration failed for package 'RPostgres'
* removing 'C:/Users/Brian/Documents/R/win-library/3.1/RPostgres'
Error: Command failed (1)

**Comment by krlmlr** [comment]
Thanks. I can't seem to find this package on CRAN. Which command do you use to install it?

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.
