### ISSUE TITLE
Think about schemas

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/RPostgres#57]
for dbWriteTable, dbReadTable, dbListColumns and others.

Perhaps a new class "SQLIdentifier"? See also https://github.com/hadley/dplyr/issues/244.

**Comment by hadley** [comment]
This probably should be an issue in DBI

**Comment by krlmlr** [comment]
It is: https://github.com/rstats-db/DBI/issues/24, https://github.com/rstats-db/DBI/issues/43.
