### ISSUE TITLE
Parameter application_name isn't set on dbConnect()

### ISSUE THREAD

**Issue by vnniyB** [rstats-db/RPostgres#75]
Current github version of dbConnect(drv=RPostgres()) does accept application_name as a parameter. 

```
dbConnect(drv=RPostgres::Postgres(), application_name = 'applicationX')
```

However when executing
`SELECT * FROM pg_stat_activity`

The application_name has not been set.

I am currently doing the following as a work around

``` r
con <- dbConnect(drv=RPostgres::Postgres())
           dbSendQuery(con, "SET application_name = 'applicationX'")
           dbDisconnect(con)
```

Check
`SELECT * FROM pg_stat_activity`
again and you can see the application_name has been set

**Comment by chochkov** [comment]
I'd like to see this progressed too; it'd definitely be an advantage over the RPostgreSQL driver. While the PR is being processed I'm using the following workaround (using RPostgreSQL for now).

```
.dbConnect <- function(drv, application_name, ...) {
  old <- Sys.getenv("PGAPPNAME")
  Sys.setenv(PGAPPNAME=application_name)
  conn <- dbConnect(...)
  Sys.setenv(PGAPPNAME=old)
  conn
}
```
