### ISSUE TITLE
dbListFields reports on dropped fields

### ISSUE THREAD

**Issue by richierocks** [rstats-db/RPostgres#76]
If you drop a column from a table, then call `dbListFields(conn, "table")`, the dropped column is included in the return value as a string like `"........pg.dropped.4........"`, where the number is the position of the dropped column.

It would be nice to have the option of not seeing these values.

**Comment by krlmlr** [comment]
Thanks. dbListFields() is currently not implemented in the `RPostgres` package (only in `RPostgreSQL`), but we should keep that in mind.
