### ISSUE TITLE
dbWriteTable with subset of columns and specified schema

### ISSUE THREAD

**Issue by ideamotor** [rstats-db/RPostgres#77]
Something that would be very useful (if not critical) would be a dbWriteTable equivalent where you can let the database handle automatically incrementing primary keys, or other additional fields as needed, as well the ability to specify the schema. You can do this with [rpg's write_table](http://www.inside-r.org/node/262690) and you can at least handle keys with [caroline's dbWriteTable2](http://www.inside-r.org/packages/cran/caroline/docs/dbWriteTable2).

**Comment by krlmlr** [comment]
Thanks. There will be schema support in the future: https://github.com/rstats-db/DBI/issues/24. Could you please show an example where updating a table with autoincrement columns fails?

**Comment by ideamotor** [comment]
I just tried again with latest version and it works.

```r
library(RPostgres)
con <- dbConnect(RPostgres::Postgres(), dbname="postgres", user="postgres",
                 password=readLines("/database/p"),host="localhost",port="5469")
query <- "DROP TABLE IF EXISTS public.example;"
dbSendQuery(con,statement = paste(query))
query <- "CREATE TABLE public.example (id SERIAL, val1 NUMERIC, val2 NUMERIC);"
dbSendQuery(con,statement = paste(query))
values <- data.frame(val1 = rep(1,10), val2 = rep(11,10))
dbWriteTable(con,"example",values, append = TRUE)
dbFetch(dbSendQuery(con,statement = paste("SELECT * FROM public.example;")))
values <- data.frame(val1 = rep(1,10))
dbWriteTable(con,"example",values, append = TRUE)
dbFetch(dbSendQuery(con,statement = paste("SELECT * FROM public.example;")))
```

That's terrific. If we can get schemas I think we'll be good to go.

**Comment by krlmlr** [comment]
Thanks for the heads-up.
