### ISSUE TITLE
undefined symbol: __gmpn_cnd_sub_n

### ISSUE THREAD

**Issue by stevenpollack** [rstats-db/RPostgres#80]
On ubuntu 15.10, when I download `R` through `conda install -c r`, and then try to install with `install_github` -- as indicated in the README -- I get the following error:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/steven/anaconda/lib/R/library/RPostgres/libs/RPostgres.so':
  /usr/lib/x86_64-linux-gnu/libhogweed.so.4: undefined symbol: __gmpn_cnd_sub_n
```
Note that DBI, BH, and Rcpp all got installed (without errors) with `install_github`.

**Comment by krlmlr** [comment]
Thanks. Could you please try to replicate it in a fresh Docker container?

**Comment by stevenpollack** [comment]
Can you link me to an explanation of how I can do this? I know nothing about docker.

**Comment by krlmlr** [comment]
That's fine. How do I install conda in Ubuntu 15.10? I'll try then myself.

**Comment by stevenpollack** [comment]
- Pick up the [miniconda](http://conda.pydata.org/miniconda.html) installer
- run the shell script
- add wherever you installed conda to your path
- execute

    ```shell
    conda install -c r r r-devtools
    ```
this sets the conda channel to `r` and then installs the packages `r` and `devtools`. From there, `R` should be available to you from wherever you installed conda.

I'd like to know how to recreate this issue with docker, though: can you point me to some literature? Or other examples that people have provided, here?

**Comment by krlmlr** [comment]
I'll set up a GitHub repo. You can also look up rocker-org on GitHub for some images that install R using apt-get.

**Comment by krlmlr** [comment]
I have created a Dockerfile: https://github.com/krlmlr/conda-r. Clone the repo and build the container using

```
docker build
```

(of course, you need to install docker first).

This file installs libpq-dev via apt-get install, and then RPostgres via devtools::install_github. It works for me when I use ubuntu:latest as base, now trying ubuntu:15.10 .

**Comment by krlmlr** [comment]
Just updated the Dockerfile to Ubuntu 15.10. Here, even installing DBI from GitHub fails:

```
Step 13 : RUN Rscript -e "httr::set_config( httr::config( ssl_verifypeer = 0L ) ); devtools::install_github(c('rstats-db/DBI'), dep = FALSE)"
 ---> Running in c7b5b33ba5b6
Downloading GitHub repo rstats-db/DBI@master
Installing DBI
'/root/miniconda2/lib64/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  '/tmp/RtmpKQbAoy/devtools72efba29e/rstats-db-DBI-9da78f3'  \
  --library='/root/miniconda2/lib/R/library' --install-tests 

* installing *source* package 'DBI' ...
** libs
g++ -I/root/miniconda2/lib/R/include -DNDEBUG  -I/root/miniconda2/include -I"/root/miniconda2/lib/R/library/Rcpp/include"   -fpic  -I/root/miniconda2/include  -c RcppExports.cpp -o RcppExports.o
g++ -I/root/miniconda2/lib/R/include -DNDEBUG  -I/root/miniconda2/include -I"/root/miniconda2/lib/R/library/Rcpp/include"   -fpic  -I/root/miniconda2/include  -c sqldelim.cpp -o sqldelim.o
g++ -shared -L/root/miniconda2/lib64/R/lib -L/root/miniconda2/lib -lgfortran -o DBI.so RcppExports.o sqldelim.o -L/root/miniconda2/lib64/R/lib -lR
installing to /root/miniconda2/lib/R/library/DBI/libs
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/root/miniconda2/lib/R/library/DBI/libs/DBI.so':
  /root/miniconda2/lib/R/library/DBI/libs/DBI.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4_
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/root/miniconda2/lib/R/library/DBI'
Error: Command failed (1)
Execution halted
make: *** [build] Error 1
```

I don't know conda at all, I'm at a loss. Note that ubuntu:latest just works with the same Dockerfile.

**Comment by stevenpollack** [comment]
Here's the thing, I'm neither a conda wizard, nor do I understand anything about shared objects...

I've put together that `undefined symbol` errors are symptoms of "incorrectly linked" libraries but:

1. I don't really know what that means
2. I've seen people use `ldd` to diagnose these errors, but it's all cryptic to me.

Thoughts?

**Comment by stevenpollack** [comment]
Okay, I forked your repo and played around. I managed to get `DBI` to install by having conda install `gcc`, but I'm still left with 
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/root/miniconda3/lib/R/library/RPostgres/libs/RPostgres.so':
  /usr/lib/x86_64-linux-gnu/libhogweed.so.4: undefined symbol: __gmpn_cnd_sub_n
```
during `RPostgres` installation.

I've got crappy internet, so I have to build this travis (for speed purposes): you can check out the log [here](https://travis-ci.org/stevenpollack/conda-r)

**Comment by krlmlr** [comment]
It's great we now can reproduce the original issue in Docker. Does that change if you use install.packages() in R to (re-)install Rcpp (and perhaps other R packages that are currently installed by conda)?

**Comment by stevenpollack** [comment]
Installing `Rcpp` and `DBI` via `devtools::install_github` [doesn't seem to work](https://travis-ci.org/stevenpollack/conda-r/builds/112251156). Trying install.packages [now](https://travis-ci.org/stevenpollack/conda-r/builds/112252949)

**Comment by krlmlr** [comment]
Could you please try `devtools::install_github(c('rstats-db/DBI', 'rstats-db/RPostgres'))`?

Thinking about the problem: I think we need to make `install.packages()` and `devtools::install_github()` use the same C/C++ compiler that was used for packaging the conda packages. Again, I don't know how.

**Comment by stevenpollack** [comment]
I get the same undefined symbol error...

**Comment by stevenpollack** [comment]
Okay, good news: I figured out what was happening.

1. RPostgres (somehow) depends on `libhogweed.so.4`, and using `ldd` we learn that
 
    ```bash
 $ ldd /usr/lib/x86_64-linux-gnu/libhogweed.so.4
 linux-vdso.so.1 =>  (0x00007ffc707df000)
 libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f24a299d000)
 libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f24a271d000)
 libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f24a2352000)
 /lib64/ld-linux-x86-64.so.2 (0x000055852b6ef000)
``` 
2. the problem is `undefined symbol: __gmpn_cnd_sub_n`, so I took a gamble and assumed this had to do with `libgmp.so.10`... Some googling around shows that this symbol shows up after GMP >= 6.0.0.
3. The latest version of GMP is 6.1.0, however, the version conda installs is 5.1.2-2. Biting the bullet, I found some [random guy's](https://anaconda.org/ostrokach/gmp/files) conda package of GMP 6.0.0a, and decided to have conda do it's thing for the installation of `devtools`, and afterwards to upgrade GMP.
4. Finally, I (sym)linked `libgmp.so.10` to the version provided by conda... See the [Dockerfile](https://github.com/stevenpollack/conda-r/blob/master/Dockerfile)

Everything installs, but I've been too lazy to start up an instance of `postgres` to test that it actually works. Would you be willing to write up a small test for me?

**Comment by stevenpollack** [comment]
Nevermind, just tested it. Will update my travis.yml.

I guess we can consider this issue closed, eh?

**Comment by krlmlr** [comment]
Thanks for digging out the reason and finding a workaround/solution. I'm sure this will be helpful to other users.
