### ISSUE TITLE
Permission denied  openssl

### ISSUE THREAD

**Issue by Altons** [rstats-db/RPostgres#9]
@hadley 

Not sure if this is the right please but here I go

I tried to installed Rpostgres in my other Mac and got this error:

```R
Error: Permission denied - /usr/local/etc/openssl
Warning: Bottle installation failed: building from source.
==> Downloading https://www.openssl.org/source/openssl-1.0.1g.tar.gz
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.1g --openssldir=/usr/local/etc/openssl zlib-dynamic shared enable-cms darwin64-x86_64-cc enable-ec_nistp_64_gcc_128
==> make depend
==> make
==> make test
==> make install MANDIR=/usr/local/Cellar/openssl/1.0.1g/share/man MANSUFFIX=ssl
i2d_SSL_SESSION.3ssl => d2i_SSL_SESSION.3ssl
installing man3/ssl.3ssl
SSL.3ssl => ssl.3ssl
Cannot create directory /usr/local/etc/openssl: Permission denied
make: *** [install_sw] Error 13
Error: Homebrew doesn't know what compiler versions ship with your version
of Xcode (6.1.1). Please `brew update` and if that doesn't help, file
an issue with the output of `brew --config`:
  https://github.com/Homebrew/homebrew/issues

Note that we only track stable, released versions of Xcode.
```

After updating brew and accepting Terms & Conditions for my Xcode Version 6.1.1 (6A2008a) (stupid automatic updates) the issue persisted when the solution struck me like a lighting bolt (a bit dramatic)  ***it was a permission issue***  (in my defence, the homebrew message is really misleading!) 

so I fixed it with the following:

```bash
sudo chown -R $USER:admin /usr/local
```

Fingers crossed future generations will read this and won't ask the same question over and over. ;-)

**Comment by hadley** [comment]
@jeroenooms any thoughts?

**Comment by jeroenooms** [comment]
I don't think this is related to RPostgres, it is a problem with your current brew installation. When you install brew, it asks you for sudo, specifically to set the permissions on `/usr/local`. One reason this might happen is if you have multiple users on osx, and you are using brew with another user than the one who installed it.

I'm not sure if there is a way to work around that. Also on osx you need to accept the license before you can use the compiler; there is little we can do about that.
