### ISSUE TITLE
Installation problem with devtools 1.12

### ISSUE THREAD

**Issue by jenast** [rstats-db/RPostgres#99]
Install_github("rstats-db/RPostgres") fails on two Windows 7 machines, running R 3.3.1 and devtools 1.12.0

Error message:
"> install_github("rstats-db/RPostgres")
Downloading GitHub repo rstats-db/RPostgres@master
from URL https://api.github.com/repos/rstats-db/RPostgres/zipball/master
Error: running command '"C:/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 2"

After downgrading to devtools 2.10, the installation works fine. I'm not sure whether the problem lies with devtools or RPostgres so I will open an issue at both repositories.

Thanks for the efforts!

Jens

**Comment by krlmlr** [comment]
devtools issue: https://github.com/hadley/devtools/issues/1347.

If it works with older devtools, it's most likely a devtools problem. Can you install a downloaded `.tar.gz` file via `install.packages(tar.gz, repos = NULL)`?

**Comment by jenast** [comment]
Yes, installing the 0.1-2 release of the tar.gz works. 

Thanks for the suggestion and sorry for the delay.
